### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by theringlord** [yasirsiddiqui/php-google-cloud-print#1]
I grabbed the files and uploaded to my site - I changed the login as noted in example.php and I get "Login failed please check login info."
Am I missing something?

**Comment by DavidAnderson684** [comment]
@waddu: You should not have published that URL - it would have allowed someone to log in to your Google account (I assume it has timed out now - I won't try it myself!).

@yasirsiddiqui : The problem is that the ClientLogin API is deprecated, and Google have started returning this response, unless you adjust the "Allow insecure apps" setting in your Google account. You need to update your code to use OAuth2 authentication instead. (I came across this whilst hunting for a PHP example of someone doing that!).

**Comment by yasirsiddiqui** [comment]
@waddu @DavidAnderson684 I have update code to use OAuth2 authentication and now you will not face any issues as Google recommends to use OAuth2.
